version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpw
      MYSQL_USER: root
      MYSQL_DATABASE: "companiesdb"
    ports:
      - "3308:3306"
 
  myapp:
    image: company-manager